trigger: none


variables:
  FTP_SERVER: 'ftps://waws-prod-yt1-003.ftp.azurewebsites.windows.net'
  FTP_USERNAME: 'serviciointermedio\$serviciointermedio'
  remoteDirectory: '/site/wwwroot'
 

pool:
  vmImage: 'windows-latest'

steps:

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'BuildInfo'
    path: '$(Pipeline.Workspace)/BuildInfo'
  displayName: 'Descargar BuildInfo'

- powershell: |
    $buildId = Get-Content "$(Pipeline.Workspace)/BuildInfo/build_number.txt"
    echo "El número de build es: $buildId"
    echo "##vso[task.setvariable variable=SharedBuildId]$buildId"
  displayName: 'Leer número de Build y guardarlo como variable'

- script: echo "Usando Build ID $(SharedBuildId)"
  displayName: 'Usar variable en otro paso'

# Descarga el artefacto del último build del primer pipeline
- task: DownloadPipelineArtifact@2 
  inputs:
    buildVersionToDownload: specific 
    buildType: specific 
    specificBuildWithTriggering: false 
    targetPath: '$(Pipeline.Workspace)\PublishedApp' 
    project: SignalRWebsocket 
    pipeline: SignalR Pull,Build and Test 
    pipelineId: $(lastBuildId)
    artifactName: PublishedApp
# Publica los archivos al servidor FTP
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '$(FTP_SERVER)'
    username: '$(FTP_USERNAME)'
    password: 'cPGZyyzqFkzrzlbzb4ko7EXyhWFzwukFxeGFDtQyKbw9r7su5MKL8cgtZWFi' # Variable secreta configurada en Azure DevOps
    rootDirectory: '$(Pipeline.Workspace)\PublishedApp'
    remoteDirectory: '$(remoteDirectory)'
    trustSSL: true