trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  FTP_SERVER: 'ftps://waws-prod-yt1-003.ftp.azurewebsites.windows.net'
  FTP_USERNAME: 'serviciointermedio\$serviciointermedio'
  remoteDirectory: '/site/wwwroot'

steps:
# Descarga el artefacto del último build
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    buildVersionToDownload: latest
    specificBuildWithTriggering: false
  
    artifactName: 'PublishedApp'
    targetPath: '$(Pipeline.Workspace)\PublishedApp'

# Publica los archivos al servidor FTP
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '$(FTP_SERVER)'
    username: '$(FTP_USERNAME)'
    password: '$(FTP_PASSWORD)' # Variable secreta configurada en Azure DevOps
    rootDirectory: '$(Pipeline.Workspace)\PublishedApp'
    remoteDirectory: '$(remoteDirectory)'
    trustSSL: true