trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  FTP_SERVER: 'ftps://waws-prod-yt1-003.ftp.azurewebsites.windows.net'
  FTP_USERNAME: 'serviciointermedio\$serviciointermedio'
  remoteDirectory: '/site/wwwroot'

steps:
- task: DownloadPipelineArtifact@1
  inputs:
    buildVersionToDownload: latestFromBranch
    buildType: current
    targetPath: '$(Pipeline.Workspace)\published'
    project: SignalRWebsocket
    pipeline: SignalR Pull,Build and Test
    pipelineId: 0
    artifactName: PublishedApp
# Publica los archivos al servidor FTP
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '$(FTP_SERVER)'
    username: '$(FTP_USERNAME)'
    password: 'cPGZyyzqFkzrzlbzb4ko7EXyhWFzwukFxeGFDtQyKbw9r7su5MKL8cgtZWFi' # Variable secreta configurada en Azure DevOps
    rootDirectory: '$(Pipeline.Workspace)\PublishedApp'
    remoteDirectory: '$(remoteDirectory)'
    trustSSL: true