trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline  # Referencia al primer pipeline
      source: 'andrupax94.signalRSinServicio' # Nombre del primer pipeline
      trigger: true

variables:
  FTP_SERVER: 'ftps://waws-prod-yt1-003.ftp.azurewebsites.windows.net'
  FTP_USERNAME: 'serviciointermedio\$serviciointermedio'
  remoteDirectory: '/site/wwwroot'
  lastBuildId: $[resources.pipelines.buildPipeline.outputs['setVars.lastBuildId']]
  lastBuildId2: $[resources.pipelines.buildPipeline.outputs['lastBuildId']] # Obtiene el ID del último build del primer pipeline

pool:
  vmImage: 'windows-latest'

steps:

- script: echo "Última ejecución del pipeline fuente = $(lastBuildId)---$(lastBuildId2)"


# Descarga el artefacto del último build del primer pipeline
- task: DownloadPipelineArtifact@2 
  inputs:
    buildVersionToDownload: specific 
    buildType: specific 
    specificBuildWithTriggering: false 
    targetPath: '$(Pipeline.Workspace)\PublishedApp' 
    project: SignalRWebsocket 
    pipeline: SignalR Pull,Build and Test 
    pipelineId: $(lastBuildId)
    artifactName: PublishedApp
# Publica los archivos al servidor FTP
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '$(FTP_SERVER)'
    username: '$(FTP_USERNAME)'
    password: 'cPGZyyzqFkzrzlbzb4ko7EXyhWFzwukFxeGFDtQyKbw9r7su5MKL8cgtZWFi' # Variable secreta configurada en Azure DevOps
    rootDirectory: '$(Pipeline.Workspace)\PublishedApp'
    remoteDirectory: '$(remoteDirectory)'
    trustSSL: true